deploy: 배포 테스트

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,21 +43,21 @@ jobs:
         run: yarn build
 
       # 빌드 폴더 압축 -> 압축 파일을 배포 예정
-      - name: Zip build files
-        run: zip -r dist.zip ./dist
+      # - name: Zip build files
+      #   run: zip -r dist.zip ./dist
 
       # 압축 파일 확인
-      - name: Verify Zip Build File
-        run: |
-          if [ -f dist.zip ]; then
-            echo "dist.zip found."
-            pwd
-            ls -lh dist.zip
-            du -h dist.zip
-          else
-            echo "dist.zip not found."
-            exit 1
-          fi
+      # - name: Verify Zip Build File
+      #   run: |
+      #     if [ -f dist.zip ]; then
+      #       echo "dist.zip found."
+      #       pwd
+      #       ls -lh dist.zip
+      #       du -h dist.zip
+      #     else
+      #       echo "dist.zip not found."
+      #       exit 1
+      #     fi
 
       # EC2에 압축된 빌드 파일 복사
       - name: Copy to EC2
@@ -67,7 +67,7 @@ jobs:
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_KEY }}
           port: ${{ secrets.SSH_PORT }}
-          source: dist.zip
+          source: ./dist
           target: /home/${{ secrets.SSH_USERNAME }}/nanalmoa-fe/
 
       # EC2에서 배포 스크립트 실행
