deploy: 인증 성공 테스트

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,50 +16,50 @@ jobs:
         uses: actions/checkout@v3
 
       # Node.js 설치
-      # - name: Set up Node.js
-      #   uses: actions/setup-node@v3
-      #   with:
-      #     node-version: '21.5.0'
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '21.5.0'
 
       # node_modules 캐시
-      # - name: Cache node modules
-      #   uses: actions/cache@v3
-      #   id: cache
-      #   with:
-      #     path: node_modules
-      #     key: npm-packages-${{ hashFiles('**/yarn.lock') }}
+      - name: Cache node modules
+        uses: actions/cache@v3
+        id: cache
+        with:
+          path: node_modules
+          key: npm-packages-${{ hashFiles('**/yarn.lock') }}
 
       # 모듈에 변화가 있을 때(cache-hit == true)만 의존성 설치
-      # - name: Install dependencies
-      #   if: steps.cache.outputs.cache-hit != 'true'
-      #   run: yarn install
+      - name: Install dependencies
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: yarn install
 
       # .env 파일 생성
-      # - name: Create env file
-      #   run: |
-      #     touch .env
-      #     echo "${{ secrets.PROD_ENV }}" > .env
+      - name: Create env file
+        run: |
+          touch .env
+          echo "${{ secrets.PROD_ENV }}" > .env
 
       # 레포 빌드
-      # - name: Build
-      #   run: yarn build
+      - name: Build
+        run: yarn build
 
       # 빌드 폴더 압축 -> 압축 파일을 배포 예정
-      # - name: Zip build files
-      #   run: zip -r dist.zip ./dist
+      - name: Zip build files
+        run: zip -r dist.zip ./dist
 
       # 압축 파일 확인
-      # - name: Verify Zip Build File
-      #   run: |
-      #     if [ -f dist.zip ]; then
-      #       echo "dist.zip found."
-      #       pwd
-      #       ls -lh dist.zip
-      #       du -h dist.zip
-      #     else
-      #       echo "dist.zip not found."
-      #       exit 1
-      #     fi
+      - name: Verify Zip Build File
+        run: |
+          if [ -f dist.zip ]; then
+            echo "dist.zip found."
+            pwd
+            ls -lh dist.zip
+            du -h dist.zip
+          else
+            echo "dist.zip not found."
+            exit 1
+          fi
 
       - name: Authentication test
         uses: appleboy/ssh-action@master
@@ -72,23 +72,23 @@ jobs:
             whoami
 
       # EC2에 압축된 빌드 파일 복사
-      # - name: Copy to EC2
-      #   uses: appleboy/scp-action@master
-      #   with:
-      #     host: ${{ secrets.SSH_HOST }}
-      #     username: ${{ secrets.SSH_USERNAME }}
-      #     key: ${{ secrets.SSH_KEY }}
-      #     port: ${{ secrets.SSH_PORT }}
-      #     source: dist.zip
-      #     target: /home/${{ secrets.SSH_USERNAME }}/nanalmoa-fe/
+      - name: Copy to EC2
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          key: ${{ secrets.SSH_KEY }}
+          port: ${{ secrets.SSH_PORT }}
+          source: dist.zip
+          target: /home/${{ secrets.SSH_USERNAME }}/nanalmoa-fe/
 
       # EC2에서 배포 스크립트 실행
-      # - name: Execute deploy script
-      #   uses: appleboy/ssh-action@master
-      #   with:
-      #     host: ${{ secrets.SSH_HOST }}
-      #     username: ${{ secrets.SSH_USERNAME }}
-      #     key: ${{ secrets.SSH_KEY }}
-      #     port: ${{ secrets.SSH_PORT }}
-      #     script: |
-      #       bash /home/${{ secrets.SSH_USERNAME }}/nanalmoa-fe/deploy.sh
+      - name: Execute deploy script
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          key: ${{ secrets.SSH_KEY }}
+          port: ${{ secrets.SSH_PORT }}
+          script: |
+            bash /home/${{ secrets.SSH_USERNAME }}/nanalmoa-fe/deploy.sh
